# This is use in back-end stuff - install REST Client vscode extension 
# for this to work

POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
  "secret": "blue-elephant"
}

###

GET http://localhost:3000/project/get HTTP/1.1