name: Drag And Drop Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macOS-11]
    steps:
      - name: check out on repository code
        uses: actions/checkout@v2
      - name: install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm install
